name: Pull Request Quality Gate - Ines :)!

on:
  pull_request:
    branches:
      - master
      - feature-*
      - hotfix-*

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Simulación del análisis de código SAST
      - name: Realizando análisis de SAST
        run: echo "Realizando análisis de SAST"

      # Step 3: Comprobar si existe el archivo allow_pull_request.txt
      - name: Comprobando requisitos para Pull Request
        id: check_file
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "allow_pull=true" >> $GITHUB_ENV
          else
            echo "allow_pull=false" >> $GITHUB_ENV
          fi

      # Step 4: Permitir Pull Request si allow_pull es True
      - name: Permitir Pull Request
        if: env.allow_pull == 'true'
        run: echo "Permitiendo Pull Request"

      # Step 5: Impedir Pull Request si allow_pull es False
        name: Impedir Pull Request
        if: env.allow_pull == 'false'
        run: |
          echo "Build fallida. Impidiendo Pull Request"
          exit 1

      # Step 6: Guardar archivo como artefacto
      - name: Guardar archivo de análisis
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: analysis-result
          path: allow_pull_request.txt
